Repository cylc/cylc-doc, pull requests merged in 2019-11, with the labels that each got.

#98 fix external links
  src/appendices/site-user-config-ref.rst
  src/external-triggers.rst
  src/hyperlinks.rst.include
  src/suite-design-guide/sdg-introduction.rst
  src/suite-storage-etc.rst
Labels: bug

#100 Tutorial move
  .travis.yml
  CONTRIBUTING.md
  bin/run-validate
  cylc/doc/etc/tutorial/api-keys
  cylc/doc/etc/tutorial/consolidation-tutorial/.validate
  cylc/doc/etc/tutorial/consolidation-tutorial/bin
  cylc/doc/etc/tutorial/consolidation-tutorial/lib
  cylc/doc/etc/tutorial/consolidation-tutorial/suite.rc
  cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
  cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/consolidate-observations
  cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/forecast
  cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-observations
  cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-rainfall
  cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/post-process
  cylc/doc/etc/tutorial/cylc-forecasting-suite/lib/python/mercator.py
  cylc/doc/etc/tutorial/cylc-forecasting-suite/lib/python/util.py
  cylc/doc/etc/tutorial/cylc-forecasting-suite/lib/template/map.html
  cylc/doc/etc/tutorial/cylc-forecasting-suite/suite.rc
  cylc/doc/etc/tutorial/forecast-script/forecast
  cylc/doc/etc/tutorial/forecast-script/util.py
  cylc/doc/etc/tutorial/inheritance-tutorial/suite.rc
  cylc/doc/etc/tutorial/map-template/map-template.html
  cylc/doc/etc/tutorial/retries-tutorial/.validate
  cylc/doc/etc/tutorial/retries-tutorial/suite.rc
  cylc/doc/etc/tutorial/runtime-introduction/.validate
  cylc/doc/etc/tutorial/runtime-introduction/bin/get-observations
  cylc/doc/etc/tutorial/runtime-introduction/suite.rc
  cylc/doc/etc/tutorial/runtime-tutorial/bin
  cylc/doc/etc/tutorial/runtime-tutorial/lib
  cylc/doc/etc/tutorial/runtime-tutorial/runtime
  cylc/doc/etc/tutorial/runtime-tutorial/suite.rc
  cylc/doc/etc/tutorial/test-data/rainfall.csv
  cylc/doc/etc/tutorial/test-data/wind_20171101T0000Z_x.csv
  cylc/doc/etc/tutorial/test-data/wind_20171101T0000Z_y.csv
  setup.py
  src/_static/tutorial
Labels: content, infrastructure

#102 jinja2: cylc logging
  src/suite-config.rst
Labels: content
