Repository cylc/cylc-doc, pull requests merged in 2020-10, with the labels that each got.

#156 Configuration file changes
  src/installation.rst
  src/suite-design-guide/general-principles.rst
  src/user-guide/task-job-submission.rst
Labels: small

#164 fix version indicator
  src/installation.rst
Labels: bug, small

#165 Fix.post mail changes
  .github/workflows/test.yml
  src/reference/api/zmq.rst
  src/suite-design-guide/general-principles.rst
  src/suites/satellite/ext-trigger/flow.cylc
  src/suites/xtrigger/xrandom/flow.cylc
  src/tutorial/furthertopics/suicide-triggers.rst
  src/user-guide/running-suites.rst
  src/user-guide/writing-suites.rst
Labels: bug, content

#166 user guide: graph branching
  src/glossary.rst
  src/suite-design-guide/general-principles.rst
  src/user-guide/index.rst
  src/user-guide/workflows.rst
  src/user-guide/writing-suites.rst
  src/user-guide/writing-suites/configuration.rst
  src/user-guide/writing-suites/empy.rst
  src/user-guide/writing-suites/index.rst
  src/user-guide/writing-suites/jinja2.rst
  src/user-guide/writing-suites/parameterized-tasks.rst
  src/user-guide/writing-suites/runtime.rst
  src/user-guide/writing-suites/scheduling.rst
Labels: content
