Repository cylc/cylc-doc, pull requests merged in 2021-07, with the labels that each got.

#259 config: make --sparse the default
  src/7-to-8/cheat-sheet.rst
  src/tutorial/furthertopics/inheritance.rst
  src/tutorial/runtime/configuration-consolidation/families.rst
  src/tutorial/runtime/configuration-consolidation/index.rst
  src/tutorial/runtime/configuration-consolidation/parameters.rst
  src/user-guide/writing-workflows/runtime.rst
  src/workflows/inherit/multi/one/flow.cylc
Labels: small

#264 discourse badge
  src/index.rst
Labels: small

#262 portability: patch mac os dns issues
  src/installation.rst
Labels: content, small

#252 symlink dirs cli docs
  src/glossary.rst
  src/user-guide/installing-workflows.rst
  src/user-guide/running-workflows.rst
  src/user-guide/writing-workflows/runtime.rst
Labels: content

#273 Major Changes - Cylc Install - Rose Stem
  src/7-to-8/major-changes/cylc-install.rst
  src/7-to-8/major-changes/platforms.rst
  src/7-to-8/summary.rst
Labels: content

#269 Refactor Running Workflows
  src/user-guide/index.rst
  src/user-guide/running-workflows/disaster-recovery.rst
  src/user-guide/running-workflows/index.rst
  src/user-guide/running-workflows/running-workflows.rst
  src/user-guide/writing-workflows/external-triggers.rst
  src/user-guide/writing-workflows/runtime.rst
  src/user-guide/writing-workflows/scheduling.rst
Labels: content

#276 removed outdated disaster recovery file
  src/user-guide/running-workflows/disaster-recovery.rst
Labels: bug
