Repository cylc/cylc-doc, pull requests merged in 2021-12, with the labels that each got.

#354 setup: bump cylc-sphix-extensions to 1.3.4
  setup.py
Labels: infrastructure

#362 Add docs for cycle point options in restart
  src/user-guide/running-workflows/scheduler-start-up.rst
Labels: content

#361 Workflow config log files docs
  src/user-guide/running-workflows/authentication-files.rst
  src/user-guide/running-workflows/scheduler-start-up.rst
Labels: content

#365 belmullet → aldergrove
  cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
  cylc/doc/etc/tutorial/runtime-introduction/flow.cylc
  cylc/doc/etc/tutorial/runtime-tutorial/flow.cylc
Labels: small

#344 platforms: document how to run jobs on a homeless platform.
  src/reference/config/writing-platform-configs.rst
Labels: content
