Repository cylc/cylc-doc, pull requests merged in 2021-11, with the labels that each got.

#312 actions: add cylc-uiserver to build env
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
Labels: infrastructure

#310 Doc overhaul
  src/7-to-8/caveats.rst
  src/7-to-8/cheat-sheet.rst
  src/7-to-8/major-changes/before-you-start.rst
  src/7-to-8/major-changes/cylc-install.rst
  src/7-to-8/major-changes/platforms.rst
  src/7-to-8/major-changes/suicide-triggers.rst
  src/7-to-8/summary.rst
  src/glossary.rst
  src/hyperlinks.rst.include
  src/index.rst
  src/installation.rst
  src/reference/architecture/ui-server.rst
  src/tutorial/furthertopics/family-triggers.rst
  src/tutorial/furthertopics/index.rst
  src/tutorial/furthertopics/inheritance.rst
  src/tutorial/furthertopics/queues.rst
  src/tutorial/furthertopics/retries.rst
  src/tutorial/furthertopics/suicide-triggers.rst
  src/tutorial/index.rst
  src/tutorial/introduction.rst
  src/tutorial/runtime/configuration-consolidation/families.rst
  src/tutorial/runtime/configuration-consolidation/jinja2.rst
  src/tutorial/runtime/configuration-consolidation/parameters.rst
  src/tutorial/runtime/index.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/tutorial/scheduling/datetime-cycling.rst
  src/tutorial/scheduling/further-scheduling.rst
  src/tutorial/scheduling/graphing.rst
  src/tutorial/scheduling/index.rst
  src/tutorial/scheduling/integer-cycling.rst
Labels: content

#317 GH Actions: Fix a couple of issues
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
Labels: infrastructure, small

#300 Authorization documentation
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/etc/met-office-sites.dat
  src/7-to-8/caveats.rst
  src/7-to-8/summary.rst
  src/reference/architecture/ui-server.rst
  src/user-guide/index.rst
  src/user-guide/sharing-access-to-workflows.rst
  src/user-guide/writing-workflows/jinja2.rst
Labels: content

#320 companion to https://github.com/cylc/cylc-flow/pull/4521
  src/user-guide/running-workflows/running-workflows.rst
Labels: content

#302 No recursive installation
  src/user-guide/installing-workflows.rst
Labels: content

#326 File installation, symlink dirs, remote init update
  src/7-to-8/summary.rst
  src/reference/config/writing-platform-configs.rst
  src/user-guide/running-workflows/scheduler-start-up.rst
  src/workflow-design-guide/general-principles.rst
Labels: content

#342 8.0b3 installation changes
  .github/actions/create-conda-envs/action.yml
  .github/workflows/conda-build-test.yml
  .github/workflows/create-conda-envs.yml
  .github/workflows/deploy.yml
  Makefile
  setup.py
  src/conf.py
  src/hyperlinks.rst.include
  src/installation.rst
  src/lib/cylc_release.py
  src/reference/environments/basic-3.7.yml
  src/reference/environments/basic.yml
  src/reference/environments/conda.rst
  src/reference/environments/envs/cylc-all.yml
  src/reference/environments/envs/cylc-flow-anaconda.yml
  src/reference/environments/envs/cylc-flow-base.yml
  src/reference/environments/envs/cylc-flow-with-python.yml
  src/reference/environments/envs/cylc-flow.yml
  src/reference/environments/envs/cylc-rose.yml
  src/reference/environments/envs/cylc-uiserver-with-traefik-proxy.yml
  src/reference/environments/envs/cylc-uiserver-without-jupyterhub.yml
  src/reference/environments/envs/cylc-uiserver.yml
  src/reference/environments/example_envs.rst
  src/reference/environments/gui.yml
  src/reference/environments/rose.yml
  src/reference/index.rst
Labels: content, infrastructure
