Repository cylc/cylc-doc, pull requests merged in 2021-09, with the labels that each got.

#286 Document template vars
  src/user-guide/writing-workflows/jinja2.rst
Labels: content

#290 Add docs for cylc clean
  src/7-to-8/cheat-sheet.rst
  src/7-to-8/major-changes/cylc-install.rst
  src/7-to-8/summary.rst
  src/user-guide/index.rst
  src/user-guide/installing-workflows.rst
  src/user-guide/removing-workflows.rst
Labels: content

#265 tutorial workflow - added alternative wind obs data retrieval
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/etc/met-office-sites.dat
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/flow.cylc
  src/tutorial/runtime/configuration-consolidation/families.rst
  src/tutorial/runtime/configuration-consolidation/index.rst
  src/tutorial/runtime/configuration-consolidation/jinja2.rst
  src/tutorial/runtime/configuration-consolidation/parameters.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/tutorial/scheduling/datetime-cycling.rst
Labels: bug, tutorial-workflow

#293 conda builds
  .github/workflows/conda-build-test.yml
  src/reference/environments/basic-3.7.yml
  src/reference/environments/basic.yml
  src/reference/environments/example_envs.rst
  src/reference/environments/gui.yml
  src/reference/environments/rose.yml
  src/reference/index.rst
Labels: content, question

#295 make discourse button direct to discourse page
  src/index.rst
Labels: small
