Repository cylc/cylc-doc, pull requests merged in 2021-03, with the labels that each got.

#205 Fix build failure and move apt install step to its own action
  .github/actions/install-dependencies/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
Labels: bug, infrastructure

#207 Update docs for implicit/naked tasks
  cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
  cylc/doc/etc/tutorial/retries-tutorial/.validate
  cylc/doc/etc/tutorial/runtime-introduction/.validate
  src/glossary.rst
  src/suite-design-guide/efficiency.rst
  src/suites/empy/cities/flow.cylc
  src/suites/inherit/single/one/flow.cylc
  src/suites/inherit/single/two/flow.cylc
  src/suites/jinja2/cities/flow.cylc
  src/suites/jinja2/defaults/flow.cylc
  src/suites/queues/flow.cylc
  src/tutorial/furthertopics/suicide-triggers.rst
  src/tutorial/runtime/configuration-consolidation/jinja2.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/scheduling/datetime-cycling.rst
  src/tutorial/scheduling/graphing.rst
  src/tutorial/scheduling/integer-cycling.rst
  src/user-guide/running-suites.rst
  src/user-guide/writing-suites/runtime.rst
  src/user-guide/writing-suites/scheduling.rst
Labels: content

#201 Cylc install/reinstall docs
  src/glossary.rst
  src/plugins/cylc-rose.rst
  src/suite-design-guide/general-principles.rst
  src/tutorial/furthertopics/message-triggers.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/user-guide/external-triggers.rst
  src/user-guide/index.rst
  src/user-guide/installing-workflows.rst
  src/user-guide/running-suites.rst
  src/user-guide/suite-name-reg.rst
  src/user-guide/writing-suites/jinja2.rst
  src/user-guide/writing-suites/runtime.rst
  src/user-guide/writing-suites/scheduling.rst
Labels: content

#214 Update task communication documentation
  src/user-guide/running-suites.rst
Labels: content

#219 Fix "make clean"
  Makefile
Labels: infrastructure, small

#227 fix tutorial use of install command
  cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
  cylc/doc/etc/tutorial/runtime-introduction/.validate
Labels: small

#221 Configurable source dirs docs
  src/user-guide/installing-workflows.rst
Labels: content

#223 Unify get-config
  src/suite-design-guide/efficiency.rst
  src/suites/inherit/multi/one/flow.cylc
  src/suites/inherit/single/two/flow.cylc
  src/tutorial/furthertopics/inheritance.rst
  src/tutorial/runtime/configuration-consolidation/families.rst
  src/tutorial/runtime/configuration-consolidation/index.rst
  src/tutorial/runtime/configuration-consolidation/jinja2.rst
  src/tutorial/runtime/configuration-consolidation/parameters.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/tutorial/scheduling/graphing.rst
  src/user-guide/writing-suites/configuration.rst
  src/user-guide/writing-suites/jinja2.rst
  src/user-guide/writing-suites/runtime.rst
Labels: content

#229 Fix nightly build
  .github/workflows/nightly.yml
Labels: infrastructure, small

#232 Add links to doc builds in readme
  Makefile
  README.md
Labels: small
