Repository cylc/cylc-doc, pull requests merged in 2022-02, with the labels that each got.

#391 Workaround pygraphviz 1.8 bug for pip 22 / py 3.7
  .github/actions/install-dependencies/action.yml
Labels: infrastructure, small

#392 Update script item style reccommendations
  src/workflow-design-guide/style-guide.rst
Labels: content, small

#388 Fix additional tutorials
  src/7-to-8/summary.rst
  src/tutorial/furthertopics/broadcast.rst
  src/tutorial/furthertopics/clock-triggered-tasks.rst
  src/tutorial/furthertopics/family-triggers.rst
  src/tutorial/furthertopics/index.rst
  src/tutorial/furthertopics/inheritance.rst
  src/tutorial/furthertopics/message-triggers.rst
  src/tutorial/furthertopics/queues.rst
  src/tutorial/furthertopics/retries.rst
  src/user-guide/writing-workflows/scheduling.rst
Labels: content

#395 design guide: update for cylc 8
  src/workflow-design-guide/general-principles.rst
  src/workflow-design-guide/portable-workflows.rst
  src/workflow-design-guide/style-guide.rst
Labels: content

#394 728: add instructions for re-running from scratch
  src/7-to-8/major-changes/play-pause-stop.rst
Labels: content, small

#400 more spelling fixes
  src/7-to-8/caveats.rst
  src/glossary.rst
  src/reference/config/file-format.rst
  src/tutorial/scheduling/datetime-cycling.rst
  src/tutorial/scheduling/further-scheduling.rst
  src/user-guide/task-implementation/job-submission.rst
  src/user-guide/writing-workflows/scheduling.rst
  src/workflow-design-guide/general-principles.rst
  src/workflow-design-guide/portable-workflows.rst
Labels: small

#399 Improve reload docs + couple small fixes
  src/7-to-8/caveats.rst
  src/user-guide/running-workflows/scheduler-start-up.rst
Labels: content, small

#404 fix small rst errors
  src/reference/config/writing-platform-configs.rst
Labels: small

#405 Convert to setup.cfg / PEP 517
  pyproject.toml
  setup.cfg
  setup.py
Labels: infrastructure

#408 Add note on markupsafe
  src/installation.rst
Labels: small

#409 Revert markupsafe thingies
  .github/workflows/test.yml
  setup.cfg
  src/installation.rst
Labels: small

#406 Fix build error due to intersphinx failing to find zmq class
  src/conf.py
Labels: bug, infrastructure, small
