Repository cylc/cylc-doc, pull requests merged in 2022-08, with the labels that each got.

#501 Add Spellchecking to Cylc Doc
  .github/workflows/test.yml
  .gitignore
  setup.cfg
  src/conf.py
  src/dictionaries/proper_nouns
  src/dictionaries/words
  src/reference/config/writing-platform-configs.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/user-guide/sharing-access-to-workflows.rst
Labels: infrastructure

#518 user guide: document jinja2 debugging
  src/img/task-job-icons/README
  src/user-guide/writing-workflows/jinja2.rst
Labels: content, small

#520 Bump min python to 3.8
  .github/dependabot.yml
  .github/workflows/create-conda-envs.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  .github/workflows/undeploy.yml
  setup.cfg
Labels: infrastructure, dependencies

#517 728: improve rose suite-run migration docs
  src/7-to-8/major-changes/cylc-install.rst
Labels: content

#530 Fix deprecation warnings for spelling
  src/reference/config/writing-platform-configs.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/user-guide/sharing-access-to-workflows.rst
Labels: small

#529 typo fix
  README.md
Labels: small
