Repository cylc/cylc-doc, pull requests merged in 2022-10, with the labels that each got.

#547 Cherry pick from master onto 8.0.x
  README.md
  src/tutorial/furthertopics/retries.rst
  src/tutorial/scheduling/datetime-cycling.rst
  src/user-guide/sharing-access-to-workflows.rst
  src/user-guide/writing-workflows/scheduler.rst
Labels: small

#548 GH Actions: upgrade to `ubuntu-latest`; use conda to install graphviz
  .github/actions/install-dependencies/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  .github/workflows/undeploy.yml
Labels: infrastructure

#552 GH Actions: Install correct branches of other libs
  .github/workflows/test.yml
Labels: infrastructure, small

#534 Install Target and Platform Update
  src/7-to-8/caveats.rst
  src/7-to-8/major-changes/cylc-install.rst
  src/7-to-8/major-changes/platforms.rst
  src/glossary.rst
  src/installation.rst
  src/reference/config/writing-platform-configs.rst
  src/user-guide/installing-workflows.rst
  src/user-guide/sharing-access-to-workflows.rst
  src/user-guide/writing-workflows/scheduler.rst
Labels: content

#553 Fix spellcheck on GH Actions
  .github/actions/install-dependencies/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  src/dictionaries/words
Labels: infrastructure

#554 Consolidate task polling documentation and correct the info on regular polling
  src/user-guide/running-workflows/tracking-task-state.rst
  src/user-guide/task-implementation/job-submission.rst
Labels: content

#563 remove alternative spellings of paramete?ri[sz]e
  src/dictionaries/words
  src/glossary.rst
  src/tutorial/runtime/configuration-consolidation/index.rst
  src/tutorial/runtime/configuration-consolidation/jinja2.rst
  src/tutorial/runtime/configuration-consolidation/parameters.rst
  src/user-guide/running-workflows/task-job-states.rst
  src/user-guide/writing-workflows/parameterized-tasks.rst
Labels: small
