Repository cylc/cylc-doc, pull requests merged in 2022-06, with the labels that each got.

#467 Add note on Jinja2 zero-padded integers
  src/7-to-8/major-changes/python-2-3.rst
Labels: content, small

#483 Fix workflow ID inconsistency
  CONTRIBUTING.md
  src/tutorial/runtime/introduction.rst
Labels: small

#475 auto restart: add note about enabling plugin
  src/user-guide/writing-workflows/scheduler.rst
Labels: content
