Repository cylc/cylc-doc, pull requests merged in 2022-04, with the labels that each got.

#458 xtriggers: remove outdated adoption warning
  src/user-guide/writing-workflows/external-triggers.rst
Labels: small

#452 Reload triggers remote file installation documentation
  src/7-to-8/summary.rst
  src/glossary.rst
  src/user-guide/running-workflows/scheduler-start-up.rst
Labels: small

#462 Add docs on optional dependencies
  src/installation.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/scheduling/datetime-cycling.rst
Labels: content, small

#460 Update docs re: validation
  src/7-to-8/major-changes/compatibility-mode.rst
  src/7-to-8/major-changes/config-changes.rst
  src/7-to-8/summary.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/scheduling/graphing.rst
  src/user-guide/installing-workflows.rst
  src/user-guide/writing-workflows/scheduling.rst
Labels: content

#461 Update workflow installation docs
  src/7-to-8/major-changes/cylc-install.rst
  src/conf.py
  src/user-guide/installing-workflows.rst
Labels: content
