Repository cylc/cylc-doc, pull requests merged in 2022-01, with the labels that each got.

#373 Prevent 404.html from showing up in sidebar versions
  bin/version
Labels: small

#366 Update notes about disallowed dir names in workflow name
  src/user-guide/installing-workflows.rst
Labels: content, small

#376 Caution note for platform select by subshell added.
  src/user-guide/writing-workflows/runtime.rst
Labels: content, small

#369 Improve symlink dirs documentation
  src/7-to-8/summary.rst
  src/user-guide/installing-workflows.rst
Labels: content

#371 Move tutorials
  .github/workflows/test_tutorial_workflow.yml
  bin/run-validate
  cylc/doc/etc/tutorial/api-keys
  cylc/doc/etc/tutorial/consolidation-tutorial/.validate
  cylc/doc/etc/tutorial/consolidation-tutorial/bin
  cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
  cylc/doc/etc/tutorial/consolidation-tutorial/lib
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/.validate
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/consolidate-observations
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/forecast
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/bin/post-process
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/etc/met-office-sites.dat
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/flow.cylc
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/lib/python/mercator.py
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/lib/python/util.py
  cylc/doc/etc/tutorial/cylc-forecasting-workflow/lib/template/map.html
  cylc/doc/etc/tutorial/forecast-script/forecast
  cylc/doc/etc/tutorial/forecast-script/util.py
  cylc/doc/etc/tutorial/inheritance-tutorial/flow.cylc
  cylc/doc/etc/tutorial/map-template/map-template.html
  cylc/doc/etc/tutorial/message-trigger-tutorial/bin/random.sh
  cylc/doc/etc/tutorial/retries-tutorial/.validate
  cylc/doc/etc/tutorial/retries-tutorial/flow.cylc
  cylc/doc/etc/tutorial/runtime-introduction/.validate
  cylc/doc/etc/tutorial/runtime-introduction/bin/get-observations
  cylc/doc/etc/tutorial/runtime-introduction/flow.cylc
  cylc/doc/etc/tutorial/runtime-tutorial/bin
  cylc/doc/etc/tutorial/runtime-tutorial/flow.cylc
  cylc/doc/etc/tutorial/runtime-tutorial/lib
  cylc/doc/etc/tutorial/runtime-tutorial/runtime
  cylc/doc/etc/tutorial/test-data/rainfall.csv
  cylc/doc/etc/tutorial/test-data/wind_20171101T0000Z_x.csv
  cylc/doc/etc/tutorial/test-data/wind_20171101T0000Z_y.csv
  setup.py
Labels: tutorial-workflow

#378 Delete broken tutorial symlink
  src/_static/tutorial
Labels: bug, small, tutorial-workflow

#330 Minor correction to DB diagram
  README.md
  src/ext/database_diagram.py
  src/release-note.rst
Labels: small

#387 fix heading levels
  src/reference/config/writing-platform-configs.rst
Labels: small
