Repository cylc/cylc-doc, pull requests merged in 2022-03, with the labels that each got.

#416 Quick summary refactor
  src/7-to-8/major-changes/compatibility-mode.rst
  src/7-to-8/major-changes/config-changes.rst
  src/7-to-8/major-changes/index.rst
  src/7-to-8/major-changes/scheduling.rst
  src/7-to-8/major-changes/task-job-states.rst
  src/7-to-8/major-changes/ui.rst
  src/7-to-8/summary.rst
  src/installation.rst
  src/reference/architecture/index.rst
  src/reference/config/global.rst
  src/reference/config/ui-server.rst
  src/user-guide/running-workflows/scheduler-start-up.rst
  src/user-guide/sharing-access-to-workflows.rst
  src/workflow-design-guide/general-principles.rst
Labels: content

#419 Tidied the slides
  src/tutorial/runtime/configuration-consolidation/index.rst
  src/tutorial/runtime/introduction.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/tutorial/scheduling/datetime-cycling.rst
  src/tutorial/scheduling/graphing.rst
  src/tutorial/scheduling/integer-cycling.rst
Labels: content

#423 Improve readability of diagram
  src/user-guide/task-implementation/job-scripts.rst
Labels: small

#425 Fix nightly
  .github/actions/create-conda-envs/action.yml
  .github/actions/install-libs/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  setup.cfg
  src/_templates/versions.html
  src/conf.py
  src/reference/environments/envs/cylc-all.yml
  src/reference/environments/envs/cylc-flow-anaconda.yml
  src/reference/environments/envs/cylc-flow-base.yml
  src/reference/environments/envs/cylc-flow-with-python.yml
  src/reference/environments/envs/cylc-flow.yml
  src/reference/environments/envs/cylc-rose.yml
  src/reference/environments/envs/cylc-uiserver-with-traefik-proxy.yml
  src/reference/environments/envs/cylc-uiserver-without-jupyterhub.yml
  src/reference/environments/envs/cylc-uiserver.yml
Labels: infrastructure

#436 Fix UIS config path in docs.
  src/reference/config/ui-server.rst
  src/user-guide/sharing-access-to-workflows.rst
Labels: bug

#439 Actions: Fix create-conda-envs
  .github/actions/create-conda-envs/action.yml
  .github/workflows/create-conda-envs.yml
  .github/workflows/deploy.yml
Labels: bug, infrastructure, small

#438 Add .mailmap and add shortlog check action
  .github/workflows/shortlog.yml
  .mailmap
Labels: infrastructure, small
