Repository cylc/cylc-doc, pull requests merged in 2022-07, with the labels that each got.

#491 Small changes
  .github/actions/install-dependencies/action.yml
  .github/workflows/deploy.yml
  src/user-guide/writing-workflows/jinja2.rst
Labels: content, infrastructure, small

#490 Improve migration guide
  src/7-to-8/major-changes/cli.rst
  src/7-to-8/major-changes/compatibility-mode.rst
  src/7-to-8/major-changes/config-changes.rst
  src/7-to-8/major-changes/cylc-install.rst
  src/7-to-8/major-changes/platforms.rst
  src/7-to-8/major-changes/python-2-3.rst
  src/7-to-8/major-changes/remote-owner.rst
  src/7-to-8/major-changes/scheduling.rst
  src/7-to-8/major-changes/suicide-triggers.rst
  src/7-to-8/summary.rst
  src/conf.py
  src/glossary.rst
  src/reference/job-script-vars/index.rst
  src/reference/job-script-vars/var-list.txt
  src/user-guide/running-workflows/scheduler-start-up.rst
  src/user-guide/writing-workflows/jinja2.rst
Labels: content

#499 small change to make usage of cylc get-resources consistent.
  src/tutorial/runtime/introduction.rst
Labels: small

#503 Fix some shell variable names.
  src/workflow-design-guide/general-principles.rst
Labels: bug, small

#492 s/expected/required/g outputs.
  src/7-to-8/major-changes/compatibility-mode.rst
  src/7-to-8/major-changes/scheduling.rst
  src/7-to-8/major-changes/suicide-triggers.rst
  src/7-to-8/summary.rst
  src/glossary.rst
  src/user-guide/running-workflows/reflow.rst
  src/user-guide/running-workflows/tasks-jobs-ui.rst
  src/user-guide/running-workflows/workflow-completion.rst
  src/user-guide/writing-workflows/scheduling.rst
Labels: small

#504 clarify that run hosts should share a file system
  src/user-guide/writing-workflows/scheduler.rst
Labels: small

#509 updated task-job.png
  src/img/task-job.png
Labels: small
