Repository cylc/cylc-doc, pull requests merged in 2023-01, with the labels that each got.

#578 fix spelling
  src/user-guide/running-workflows/task-job-states.rst
Labels: small

#582 Update sphinx-rtd-theme pin to avoid broken jQuery
  setup.cfg
Labels: bug, small, dependencies

#586 Add Edit Runtime to changelog
  .github/workflows/test.yml
  src/reference/changes.rst
  src/reference/changes/edit-runtime-screenshot.png
  src/tutorial/furthertopics/broadcast.rst
  src/user-guide/running-workflows/dynamic-behaviour.rst
Labels: small

#585 Add vr to cheatsheet
  src/7-to-8/cheat-sheet.rst
Labels: content

#589 Fix endless pip backtracking for nightly
  .github/workflows/nightly.yml
Labels: infrastructure, small
