Repository cylc/cylc-doc, pull requests merged in 2023-09, with the labels that each got.

#639 Update outdated UTC mode docs
  src/workflow-design-guide/general-principles.rst
Labels: content, small

#649 GH Actions: update setup-miniconda to v2.2.0
  .github/actions/install-dependencies/action.yml
Labels: infrastructure, dependencies

#653 Fix.tutorial
  src/conf.py
  src/tutorial/runtime/runtime-configuration.rst
  src/user-guide/installing-workflows.rst
Labels: content
