Repository cylc/cylc-doc, pull requests merged in 2024-04, with the labels that each got.

#702 Changelog
  .gitignore
  src/reference/changes.rst
  src/reference/changes/ui-workspace-tabs.gif
Labels: small

#705 sync
  src/reference/changes.rst
  src/tutorial/runtime/runtime-configuration.rst
  src/user-guide/running-workflows/scheduler-log-files.rst
Labels: sync

#706 8.2.x -> master (adds branch sync workflow)
  .github/workflows/branch_sync.yml
Labels: sync

#708 Add workaround for mirror/fcm make tasks conflicting with symlink dirs (cherry-pick from master)
  .github/workflows/test.yml
  src/7-to-8/major-changes/cylc-install.rst
  src/reference/config/writing-platform-configs.rst
  src/user-guide/installing-workflows.rst
Labels: content, infrastructure, sync

#707 GH Actions: fix invalid cron schedule
  .github/workflows/branch_sync.yml
Labels: infrastructure, small

#714 Update outdated UTC mode paragraph
  src/tutorial/scheduling/datetime-cycling.rst
Labels: content, small

#715 Small spelling fix
  src/tutorial/furthertopics/inheritance.rst
Labels: small

#717 Update outdated UTC mode paragraph
  src/tutorial/scheduling/datetime-cycling.rst
Labels: sync

#721 changes: document cylc-ui#1755
  src/reference/changes.rst
  src/reference/changes/gui-n-window-selector.gif
Labels: content

#720 move page from user guide to reference
  src/reference/config/index.rst
  src/reference/config/sharing-access-to-workflows.rst
  src/user-guide/index.rst
Labels: small

#660 clarify runahead limit
  src/glossary.rst
  src/hyperlinks.rst.include
  src/img/n-window.gif
  src/user-guide/running-workflows/index.rst
  src/user-guide/running-workflows/reflow.rst
  src/user-guide/running-workflows/task-job-states.rst
  src/user-guide/running-workflows/tasks-jobs-ui.rst
  src/user-guide/writing-workflows/scheduling.rst
  src/user-guide/writing-workflows/suicide-triggers.rst
Labels: content

#723 user-guide: add interventions section
  setup.cfg
  src/conf.py
  src/user-guide/index.rst
  src/user-guide/interventions/edit-a-tasks-configuration.gui.gif
  src/user-guide/interventions/edit-the-workflow-configuration.tui.gif
  src/user-guide/interventions/index.rst
  src/user-guide/interventions/re-run-a-task.gui.gif
  src/user-guide/interventions/re-run-a-task.tui.gif
  src/user-guide/interventions/re-run-all-failed-tasks.gui.gif
  src/user-guide/interventions/re-run-multiple-tasks.gui.gif
  src/user-guide/interventions/set-a-switch-task.gui.gif
  src/user-guide/interventions/set-task-outputs.gif
  src/user-guide/interventions/set-task-outputs.gui.gif
  src/user-guide/interventions/set-task-outputs.tui.gif
  src/user-guide/interventions/set-task-prerequisites.gui.gif
  src/user-guide/running-workflows/scheduler-start-up.rst
Labels: content
