Repository cylc/cylc-doc, pull requests merged in 2025-07, with the labels that each got.

#843 Clarify shorthand
  src/reference/config/shorthand.rst
  src/tutorial/scheduling/graphing.rst
Labels: content, small

#840 Amend workflow events docs
  src/user-guide/writing-workflows/scheduler.rst
Labels: content, small

#846 Fix spelling
  src/glossary.rst
  src/user-guide/running-workflows/reflow.rst
  src/user-guide/running-workflows/workflow-completion.rst
Labels: small

#831 Fix runahead limit documentation.
  src/user-guide/writing-workflows/scheduling.rst
Labels: bug
