Repository cylc/cylc-doc, pull requests merged in 2025-08, with the labels that each got.

#857 Improve events docs
  src/user-guide/writing-workflows/runtime.rst
  src/user-guide/writing-workflows/scheduler.rst
Labels: content, small

#853 Improve Job Script Environment Variables reference
  CONTRIBUTING.md
  src/dictionaries/proper_nouns
  src/dictionaries/words
  src/reference/job-script-vars/index.rst
  src/reference/job-script-vars/var-list.rst
  src/reference/job-script-vars/var-list.txt
  src/user-guide/writing-workflows/jinja2.rst
  src/user-guide/writing-workflows/runtime.rst
Labels: content

#865 Add sphinx copybutton extension
  setup.cfg
  src/conf.py
Labels: small, dependencies
