Repository cylc/cylc-doc, pull requests merged in 2025-09, with the labels that each got.

#864 Update out-of-date info for 8.5
  .github/workflows/create-conda-envs.yml
  .github/workflows/test.yml
  src/installation.rst
  src/reference/changes.rst
Labels: content, infrastructure, small

#866 Minimum Python 3.12
  .github/workflows/create-conda-envs.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  .github/workflows/test.yml
  .github/workflows/undeploy.yml
  bin/version
  setup.cfg
  src/installation.rst
  src/lib/cylc_release.py
  src/reference/changes.rst
Labels: content, small

#823 Add supported text editors to the list
  src/user-guide/writing-workflows/configuration.rst
Labels: content, small

#856 Update screenshots
  src/7-to-8/major-changes/ui.rst
  src/img/cylc-ui-dash.png
  src/img/cylc-ui-tree.png
  src/img/installation/conda/dashboard.png
  src/img/installation/conda/hub.png
  src/img/installation/conda/treeview.png
  src/img/installation/conda/workflows.png
Labels: content, small

#878 changes: broadcast expiry
  src/reference/changes.rst
Labels: content
