Repository cylc/cylc-doc, pull requests merged in 2025-01, with the labels that each got.

#789 added a remove-task intervention to the user guide
  src/user-guide/interventions/index.rst
  src/user-guide/interventions/remove.gif
Labels: content

#793 Update installation docs
  src/dictionaries/proper_nouns
  src/installation.rst
Labels: content, small

#736 Updated docs about using ROSE_DATAC
  src/reference/job-script-vars/var-list.txt
  src/workflow-design-guide/general-principles.rst
Labels: small
